theme: jekyll-theme-minimal
title: Welcome!

description: I'm Alexander Hagerf, software engineer.<br><br>Currently working <a href="https://www.jumpshot.com/" class="textlink_green" target="_blank">@Jumpshot</a> <br>previously <a href="https://www.gooddata.com/" class="textlink_green" target="_blank">@GoodData</a> and <a href="http://www.omegapoint.se/" class="textlink_red" target="_blank">@Omegapoint</a>
